{% set name = "intake-axds" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake_axds-{{ version }}.tar.gz
  sha256: 76a6496269c8981b8ae4afba0a3502502624c671343d98f5a73d333435a19829

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - cf_pandas
    - intake
    - intake-parquet
    - intake-xarray
    - pandas
    - python >=3.6
    - requests
    - shapely

test:
  imports:
    - intake_axds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/intake-axds
  summary: Intake interface to Axiom assets
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kthyng
